Created a spiderman landing page
GomezAgustin1/test-bootcamp pull request #2
Opened 2023-06-07 17:47 UTC by GomezAgustin1

Following the next figma design
https://www.figma.com/file/vVDR2aHsMH6Y5u30ngZQNl/marvel.com-(Community)?type=design&node-id=6-2&t=bNykDeMyMxrtNw8O-0

2023-06-07 18:11 UTC, ezequiel-baruf-lenio requested changes

2023-06-07 18:11 UTC, ezequiel-baruf-lenio commented on index.html
> +          <li class="nav-link active"><a href=""></a>HOME</li>
Please link to home file

2023-06-07 18:12 UTC, ezequiel-baruf-lenio commented
This is a comment in the PR
This is a link to one commit: e20a37ce73ea8763e4666994c8ff85ae8bb06f5c

2023-06-08 19:27 UTC, SchroederSimon commented on index.html
> +        <img class="search" src="./search-icon.svg" alt="Search" width="35" />
Add a proper unit of measurement, like "35**px**"

2023-06-12 05:15 UTC, merged